In [1]:
import numpy as np
import pandas as pd
pd.set_option('display.float_format', '{:,.0f}'.format)

In [2]:
def cube_expectation(kind, stage, miracle=False, level=200, print=True):
    expectation_count = 0
    info_dict = {
        'black': {
            'rare': (0.15, 10),
            'epic': (0.035, 42),
            'unique': (0.014, 107),
        },
        'red': {
            'rare': (0.06, 25),
            'epic': (0.018, 83),
            'unique': (0.003, 500),
        },
        'add': {
            'rare': (1/21, 31),
            'epic': (1/51, 76),
            'unique': (0.007, 214),
        },
        'white_add': {
            'rare': (1/21, 31),
            'epic': (1/51, 76),
            'unique': (0.007, 214),
        },
    }
    price_dict = {
        'black': 22600000,
        'red': 12500000,
    }
    stages = ['rare', 'epic', 'unique', 'legendary']
    target_stage = stages[stages.index(stage)+1]
    miracle_status = 'On' if miracle else 'Off'

    prob, ceiling = info_dict[kind][stage]
    prob *= 2 if miracle else 1
    ceiling = int(np.ceil(ceiling / 2)) if miracle else ceiling
    price = price_dict[kind]

    for count in range(1, ceiling+1):
        expectation_count += count * (1-prob)**(count-1) * prob
    
    expectation_count += (ceiling+1) * (1-prob)**ceiling
    expectation_cost = expectation_count * (price + 20*level**2)

    if print:
        title = f'{kind:5s} cube | {stage:6s} > {target_stage:9s} | Miracle: {miracle_status:3s}'
        print(f'{title}')
        print(f'Expectation Count: {expectation_count:15.0f}')
        print(f'Expectation  Cost: {expectation_cost:15,.0f}')

    return expectation_count, expectation_cost

In [3]:
kinds = ['black', 'red']
stages = ['rare', 'epic', 'unique']
permutations = [(i, j) for i in kinds for j in stages]

In [4]:
miracle = False

counts = []
costs = []

for kind, stage in permutations:
    count, cost = cube_expectation(kind=kind, stage=stage, miracle=miracle, level=0, print=False)
    counts.append(count)
    costs.append(cost)

count_without_miracle = np.ceil(counts).reshape(2, 3)
count_without_miracle = pd.DataFrame(count_without_miracle, columns=stages, index=kinds)
cost_without_miracle = np.ceil(costs).reshape(2, 3)
cost_without_miracle = pd.DataFrame(cost_without_miracle, columns=stages, index=kinds)

display(count_without_miracle)
display(cost_without_miracle)

       rare  epic  unique
black     6    23      56
red      14    44     260

             rare        epic        unique
black 125,453,618 506,169,097 1,262,168,533
red   166,638,432 543,435,567 3,241,834,190

In [5]:
miracle = True

counts = []
costs = []

for kind, stage in permutations:
    count, cost = cube_expectation(
        kind=kind, stage=stage, miracle=miracle, level=0, print=False)
    counts.append(count)
    costs.append(cost)

count_with_miracle = np.ceil(counts).reshape(2, 3)
count_with_miracle = pd.DataFrame(count_with_miracle, columns=stages, index=kinds)
cost_with_miracle = np.ceil(costs).reshape(2, 3)
cost_with_miracle = pd.DataFrame(cost_with_miracle, columns=stages, index=kinds)

display(count_with_miracle)
display(cost_with_miracle)

       rare  epic  unique
black     3    12      29
red       7    23     130

            rare        epic        unique
black 66,470,442 257,448,481   637,867,017
red   86,769,194 275,456,020 1,623,350,901